---

name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hooray! That was your first issue, be welcome to pages, thanks for contribute!!"
        pr-message: "Mmm, right, may a god can review this one... Lets take a rest, gods working!"
