---
# .github/workflows/python.yml

name: Python CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install backend dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install poetry
          poetry lock
          poetry install
        working-directory: backend
      - name: Format backend check with Black
        run: |
          source venv/bin/activate
          black --check app/
          black --check tests/
          black --check ../scripts/
        working-directory: backend
      - name: Lint backend with Pylint
        run: |
          source venv/bin/activate
          pylint $(git ls-files '*.py')
        working-directory: backend
